{
 "title": "Nginx Monitoring Dashboard",
 "description": "A Dashboard for Nginx Monitoring with Prometheus",
 "tags": [
  "nginx",
  "monitoring",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nginx Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "Nginx Status" }
   ]
  },
  {
   "title": "Nginx Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "Requests/sec"
    }
   ]
  },
  {
   "title": "Nginx Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nginx_http_request_duration_seconds",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Nginx Exporter Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Go Goroutines" }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Nginx Exporter Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "Memory Usage" }
   ]
  }
 ]
}