name: Laravel CI

on:
  push:
    branches: [ Mehdi ]
  pull_request:
    branches: [ Mehdi ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: waste2product
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, mysqli, pdo_mysql
        coverage: xdebug

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate APP_KEY
      run: php artisan key:generate

    - name: Run migrations
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: waste2product
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    - name: Run Tests
      run: php artisan test
