name: SonarQube Analysis

on:
  push:
    branches: [ Mehdi ]
  pull_request:
    branches: [ Mehdi ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, mysqli, pdo_mysql

      - name: Copy .env
        run: cp .env.example .env

      - name: Run SonarScanner (Docker)
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e SONAR_LOGIN=${{ secrets.SONAR_TOKEN }} \
            -v ${{ github.workspace }}:/usr/src \
            sonarsource/sonar-scanner-cli
